name: Property Scraper

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Runs the job every 15 minutes
  schedule:
    - cron: "*/15 * * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # You can use a newer version if you prefer

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          # The Discord webhook URL is passed securely as an environment variable
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python scraper.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sent_listings.json
          # The following command will exit with 0 if there are no changes,
          # or with 1 if there are changes to be committed.
          # This prevents the workflow from failing if there's nothing to commit.
          git diff --staged --quiet || git commit -m "Update sent listings"
          git push
