name: Property Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    # Add this block to grant write permissions
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python scraper.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sent_listings.json
          git diff --staged --quiet || git commit -m "Update sent listings"
          git push
